###
GET http://localhost:9000/Proceso HTTP/1.1

###
POST http://localhost:9000/Lote HTTP/1.1
Content-Type: application/json

{
    "Id_usuario": 27,
    "Id_empresa": 5,
    "hash_actual_lote": "",
    "cantidad_medicamentos_lote": 0,
    "Id_medicamento": 27,
    "fecha_creacion_lote": ""
}

###
DELETE http://localhost:9000 HTTP/1.1

###
PUT http://localhost:9000 HTTP/1.1
Content-Type: application/json

