###
GET http://localhost:9000 HTTP/1.1

###
POST http://localhost:9000 HTTP/1.1
Content-Type: application/json

{
    "rif": "1518075",
    "nombre": "FarmaExpress",
    "direccion": "Maracaibo, Zulia, Venezuela"
}

###
DELETE http://localhost:9000 HTTP/1.1

###
PUT http://localhost:9000 HTTP/1.1
Content-Type: application/json

{
    "titulo": "una breve historia del tiempo",
    "autor": "Stephen Hawking",
    "edicion": 3
}