###
GET http://localhost:9000/Usuario HTTP/1.1

###
POST http://localhost:9000/Usuario HTTP/1.1
Content-Type: application/json

{
    "cedula": "11661858", 
    "nombre": "Eliaquin Jose", 
    "apellido": "Loaiza Rodriguez", 
    "correo": "eliaquinloaiza@gmail.com", 
    "telefono": "04146345193", 
    "tipo": "Persona Natural", 
    "direccion": "El Bosque III Villa 15", 
    "fecha_nacimiento": "1970=07-9",
    "id_cargo": "7",
    "id_empresa": "5"

}

###
DELETE http://localhost:9000 HTTP/1.1

###
PUT http://localhost:9000 HTTP/1.1
Content-Type: application/json

